version: '3'

services:
  php:
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
    # Comment out these volumes in production
    volumes:
      - ./:/srv:rw
      # If you develop on Linux, comment out the following volumes to just use bind-mounted project directory from host
      - /srv/var/
      - /srv/var/cache/
      - /srv/var/logs/
      - /srv/var/sessions/

  nginx:
    build:
      context: ./
      dockerfile: docker/dev/nginx/Dockerfile
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./public:/srv/public:ro

  db:
    image: mariadb:11.1.2
    environment:
      MARIADB_ROOT_PASSWORD: 'root'
      MARIADB_DATABASE: 'cosmostools'
      MARIADB_USER: 'app'
      MARIADB_PASSWORD: 'pw'
    volumes:
      - db-data:/var/lib/mysql/data:rw
    ports:
      - "3306:3306"

  redis:
    image: redis:7.2.0
    volumes:
      - redis-data:/var/lib/redis/data:rw
    ports:
      - "6379:6379"

volumes:
  db-data: {}
  redis-data: {}
